/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    private static String databaseLocation = "src/main/resources/";
    public static void main(String[] args) {
        Database database = new Database(databaseLocation);
        database.init();
        database.test();
        // database.checkUser("admin", "admin");
        database.newUser("testUser", "abc123");
    }
}
